In [1]:
import pandas as pd
from src.system import System
from src.sampler import MCMCSampler
from src.model import *
from src.priors import *

In [2]:
df1_data = {'App Mag': [13.233, 13.401], 
            'Errors': [0.1, 0.1], 
            'Filter': ['H', 'J']}
df1 = pd.DataFrame(df1_data)
df1

App Mag  Errors Filter
0   13.233     0.1      H
1   13.401     0.1      J

In [3]:
s = System(df1, 100, 0.1)
print(s.sys_priors)
print(s.plx, s.plx_err)

[LogUniformPrior(minval=0.2, maxval=1.3), UniformPrior(minval=0, maxval=14180000000.0), GaussianPrior(mu=100, sigma=0.1, no_negatives=True)]
100 0.1


In [8]:
sampler = MCMCSampler(s, num_threads=1, table_type='WD', filters=["H",'J'])

In [9]:
sampler.run_sampler(100, 0, 1, "test1.hdf5")

Starting Burn in
[2.93775049e-01 9.34395135e+09 1.00034252e+02] ['H', 'J']
[17.28836964 16.87225384]
[4.50549225e-01 2.99310679e+09 9.99852041e+01] ['H', 'J']
[12.91752537 13.24272051]
[3.31322429e-01 1.10168468e+10 9.99994465e+01] ['H', 'J']
[18.02556799 17.691043  ]
[7.07767281e-01 7.78512482e+09 1.00017990e+02] ['H', 'J']
[13.52135423 13.83203711]
[4.26424052e-01 2.19456536e+09 9.99901153e+01] ['H', 'J']
[12.72203722 13.03706238]
[4.22037875e-01 1.25230456e+10 9.99690448e+01] ['H', 'J']
[18.51707775 18.21964461]
[1.21634827e+00 1.39310800e+10 1.00068059e+02] ['H', 'J']


ValueError: Solar mass input creates invalid bounds

In [ ]:
test_params = np.array([2.17289824e-01, 1.36642406e+10, 9.99720353e+01])
df1["App Mag"]

#findMags(df1, test_params[0], test_params[1], test_params[2], filts)

array([13.233, 13.401])